// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.SlideoutNavigation;

namespace StoryboardSample
{
	public partial class EntryPoint : SlideoutNavigationController
	{
		public EntryPoint (IntPtr handle) : base (handle)
		{
            var menuLeft = Storyboard.InstantiateViewController ("menuLeft") as UIViewController;
            var menuRight = Storyboard.InstantiateViewController ("menuRight") as UIViewController;
            var home = Storyboard.InstantiateViewController ("homeScreen") as UIViewController;

            this.MenuViewLeft = menuLeft;
            this.MenuViewRight = menuRight;
            this.TopView = home;
		}
	}
}
