// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace StoryboardSample
{
	public partial class homeScreen : UIViewController
	{
		public homeScreen (IntPtr handle) : base (handle)
		{
		}
	}
}
